### ISSUE TITLE
minimal_by_hdr_and_img_gz fails on Windows

### ISSUE THREAD

**Issue by nilgoyette** [Enet4/nifti-rs#27] opened 2018-11-21 18:41 UTC
This is not a new problem, I just waited a long time to report it.

When I run `cargo test --release --features ndarray_volumes`, `minimal_by_hdr_and_img_gz` fails on Windows and WSL. Moreover, it stops the other tests from running. To see the tests from `volume.rs` and `writer.rs`, I must remove the `minimal_by_hdr_and_img_gz` test.

I didn't investigate yet but I'm probably the only one with Windows so I'll do that "soon". What we could do to confirm the problem is to tell travis to test all OS. They added Windows support in the last months.

    os:
      - windows
      - linux
      - osx
    language: rust
    ...

**Comment by Enet4** [comment] 2018-11-21 19:19
Is this a different issue from #4? But yes, whatever the problem is here, we could add osx and windows to Travis.

**Comment by nilgoyette** [comment] 2018-11-21 19:44
Hahaha, wow, I totally forgot about this issue. I'll confirm that it has the same cause and, if so, I'll fix the tests. We can't really ask other contributors or travis to use the [hack](https://fishingcatblog.wordpress.com/2016/06/01/symbolic-links-in-windows-git-and-atom/) you suggested.

**Comment by Enet4** [comment] 2018-12-05 16:54
Closing as fixed by #29.

**Closed by Enet4** 2018-12-05 16:54 UTC
